name: Update FastAPI Image Tag

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

permissions:
  contents: write

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag in values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${{ github.event.inputs.image_tag }}/" values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.event.inputs.image_tag }}"
          git push 